exp_name: "dqn_cartpole"
seed: 1
torch_deterministic: True
cuda: False
wandb_project_name: safe_dqn_filter
wandb_entity: None
env_id: "SafeCartPole-v1"
total_timesteps: 500_000
learning_rate: 2.5e-4
buffer_size: 10_000
gamma: 0.99
tau: 1.0
target_network_frequency: 500
batch_size: 128
eps_start: 1.0
eps_end: 0.05
exploration_fraction: 0.5
learning_starts: 10_000
train_frequency: 10