exp_name: "sac_inverted_pendulum"
seed: 1
torch_deterministic: True
cuda: False
wandb_project_name: safe_sac_continuous_filter
wandb_entity: None
env_id: "SafeInvertedPendulum-v1"
total_timesteps: 500_000
q_learning_rate: 3e-4
policy_learning_rate: 5e-4
buffer_size: 1_000_000
gamma: 0.99
tau: 0.05
policy_update_frequency: 2
target_network_frequency: 1
batch_size: 256
alpha: 0.3
autotune_alpha: True
learning_starts: 20_000
train_frequency: 1
eval_model: True
train_model: True
manual_mode: False
safety_filter_args:
  PROB_NEAR_BOUNDARY: 1.0
  USE_SAFETY_FILTER: True
  GAMMA_START: 0.85
  GAMMA_END: 0.99
  GAMMA_ANNEAL_STEPS: 250_000
  LRSF_SAFETY_FILTER_EPSILON: 0.57
  QCBF_SAFETY_FILTER_EPSILON: 0.99
  SAFE_MARGIN_VALUES:
    pos: 2.0
    theta: 0.2