exp_name: "sac_discrete_cartpole"
seed: 1
torch_deterministic: True
cuda: False
wandb_project_name: safe_sac_discrete_filter
wandb_entity: None
env_id: "SafeCartPole-v1"
total_timesteps: 500_000
q_learning_rate: 3e-4
policy_learning_rate: 3e-4
buffer_size: 1_000_000
gamma: 0.99
tau: 1.0
target_network_frequency: 500
batch_size: 128
alpha: 0.2
autotune_alpha: False
target_entropy_scale: 0.89
learning_starts: 20_000
train_frequency: 10
eval_model: True
train_model: True
manual_mode: False