_wandb:
    value:
        cli_version: 0.21.0
        code_path: code/scripts/safety_filter_dqn.py
        e:
            1f5l6gwnjpgw2tbm31ufw0p6zpww4fmt:
                codePath: scripts/safety_filter_dqn.py
                codePathLocal: safety_filter_dqn.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "3842080538624"
                        used: "289541771264"
                email: nr1053@princeton.edu
                executable: /home/nishrao/ENTER/envs/safe/bin/python3
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-734a507e-c6d8-4b92-3a83-f04ad0c481db
                host: saferoboticslab-workstation-4
                memory:
                    total: "98747719680"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/nishrao/Projects/HJ_avoid/scripts/safety_filter_dqn.py
                python: CPython 3.10.18
                root: /home/nishrao/Projects/HJ_avoid/scripts
                startedAt: "2025-08-06T23:37:01.542052Z"
                writerId: 1f5l6gwnjpgw2tbm31ufw0p6zpww4fmt
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.10.18
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 128
buffer_size:
    value: 10000
cuda:
    value: false
env_id:
    value: SafeCartPole-v1
eps_end:
    value: 0.05
eps_start:
    value: 1
eval_model_path:
    value: /home/nishrao/Projects/HJ_avoid/logs/safedqn_cartpole_2025-08-06_18-48-00/model/q_network.pth
exp_name:
    value: safedqn_cartpole
exploration_fraction:
    value: 0.5
gamma:
    value: 0.85
learning_rate:
    value: 0.00025
learning_starts:
    value: 10000
manual_mode:
    value: false
safety_filter_args:
    value:
        GAMMA_ANNEAL_STEPS: 400000
        GAMMA_END: 0.99
        GAMMA_START: 0.85
        SAFE_MARGIN_VALUES:
            om: 1
            pos: 2
            theta: 0.174533
            vel: 1
        SAFETY_FILTER_EPSILON: 0.57
        USE_SAFETY_FILTER: true
seed:
    value: 1
target_network_frequency:
    value: 500
tau:
    value: 1
torch_deterministic:
    value: true
total_timesteps:
    value: 750000
train_frequency:
    value: 10
train_model:
    value: false
wandb_entity:
    value: None
wandb_project_name:
    value: safe_dqn_filter
